name: innon
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  # auto_route: ^4.2.1
  cloud_firestore: ^4.2.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # flutter_mobx: ^2.0.1
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  # get_it: ^7.2.0
  google_sign_in: ^5.4.2

  intl: ^0.17.0
  provider: ^6.0.5
  to_csv: ^1.1.1
  uuid: ^3.0.7

dev_dependencies:
  # auto_route_generator: null
  change_app_package_name: ^1.1.0

  # A build system for Dart code generation and modular compilation.
  # See the following page: https://pub.dev/packages/build_runner
  build_runner: null
  flutter_test:
    sdk: flutter


  #data

  # Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and
  # inject.dart.
  # See the following page: https://pub.dev/packages/injectable_generator

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  # See the following page: https://pub.dev/packages/json_serializable
  json_serializable: ^6.1.4

  # Code generator for MobX that adds support for annotating your code with @observable, @computed,
  # @action and also creating Store classes.
  # See the following page: https://pub.dev/packages/mobx_codegen

#  # retrofit.dart is an dio client generator using source_gen and inspired by Chopper and Retrofit.
#  # See the following page: https://pub.dev/packages/retrofit_generator
#  retrofit_generator: '>=4.0.0 <5.0.0'
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
