name: innon
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cloud_firestore: ^4.2.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  firebase_messaging: ^14.2.4
  firebase_storage: ^11.0.7
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  google_sign_in: ^5.4.2
  http: ^0.13.5
  intl: ^0.17.0
  provider: ^6.0.5
  to_csv: ^1.1.1
  uuid: ^3.0.7

dev_dependencies:
  build_runner: null
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

  #data
  # Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and
  # inject.dart.
  # See the following page: https://pub.dev/packages/injectable_generator
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  # See the following page: https://pub.dev/packages/json_serializable
  json_serializable: ^6.1.4

#  # retrofit.dart is an dio client generator using source_gen and inspired by Chopper and Retrofit.
#  # See the following page: https://pub.dev/packages/retrofit_generator
#  retrofit_generator: '>=4.0.0 <5.0.0'
dependency_overrides:
  firebase_messaging_platform_interface: 4.2.13

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
